### ISSUE TITLE
Build Failed wangle has changed  member variable name in Aug.19

### ISSUE THREAD

**Issue by detective7th** [facebook/proxygen#111]
wangle TransportInfo: replace 'ssl' with 'secure' and add 'securityType'.

in deps.sh just git fetch the wangle master branch, so it happen.

**Comment by lnicco** [comment]
thanks for reporting this @detective7th

**Comment by anirudhvr** [comment]
@knekritz Want to take a look?

**Comment by knekritz** [comment]
Can you try rebasing both proxygen and wangle to master? I think this should be resolved if both are in sync on master.

**Comment by cm0n** [comment]
I have also problems with wangle my ubuntu 14.04 stops the build process:
`[ 23%] Building CXX object CMakeFiles/wangle.dir/channel/FileRegion.cpp.o
[ 25%] Building CXX object CMakeFiles/wangle.dir/channel/Pipeline.cpp.o
[ 26%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldBasedFrameDecoder.cpp.o
[ 28%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldPrepender.cpp.o
[ 30%] Building CXX object CMakeFiles/wangle.dir/codec/LineBasedFrameDecoder.cpp.o
[ 32%] Building CXX object CMakeFiles/wangle.dir/concurrent/ThreadedExecutor.cpp.o
[ 34%] Building CXX object CMakeFiles/wangle.dir/concurrent/CPUThreadPoolExecutor.cpp.o
[ 36%] Building CXX object CMakeFiles/wangle.dir/concurrent/Codel.cpp.o
[ 38%] Building CXX object CMakeFiles/wangle.dir/concurrent/GlobalExecutor.cpp.o
[ 40%] Building CXX object CMakeFiles/wangle.dir/concurrent/IOThreadPoolExecutor.cpp.o
[ 42%] Building CXX object CMakeFiles/wangle.dir/concurrent/ThreadPoolExecutor.cpp.o
[ 44%] Building CXX object CMakeFiles/wangle.dir/ssl/PasswordInFile.cpp.o
[ 46%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLContextManager.cpp.o
[ 48%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o
[ 50%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLUtil.cpp.o
[ 51%] Building CXX object CMakeFiles/wangle.dir/ssl/TLSTicketKeyManager.cpp.o
Linking CXX static library lib/libwangle.a
`
my proxygen and wangle sync with master, what can i do?

**Comment by jainarpit6** [comment]
I also have same problem as reported above while building. I think the error is not because of wangle. I can see error messages while downloading gmock-zip (see below).

__CMake Error at gmock-stamp/gmock-download.cmake:16 (message):_
  Command failed: 1
   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '$HOME/proxygen/proxygen/proxygen/wangle/wangle/gmock/src/gmock-stamp/gmock-download-impl.cmake'
  See also
    $HOME/proxygen/proxygen/proxygen/wangle/wangle/gmock/src/gmock-stamp/gmock-download-*.log
make[2]: *** [gmock/src/gmock-stamp/gmock-download] Error 1
make[1]: *** [CMakeFiles/gmock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 16%] Building CXX object CMakeFiles/wangle.dir/acceptor/TLSPlaintextPeekingCallback.cpp.o
[ 18%] Building CXX object CMakeFiles/wangle.dir/acceptor/TransportInfo.cpp.o
[ 20%] Building CXX object CMakeFiles/wangle.dir/bootstrap/ServerBootstrap.cpp.o
[ 21%] Building CXX object CMakeFiles/wangle.dir/channel/FileRegion.cpp.o
[ 23%] Building CXX object CMakeFiles/wangle.dir/channel/Pipeline.cpp.o
[ 25%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldBasedFrameDecoder.cpp.o
[ 27%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldPrepender.cpp.o
[ 29%] Building CXX object CMakeFiles/wangle.dir/codec/LineBasedFrameDecoder.cpp.o
[ 30%] Building CXX object CMakeFiles/wangle.dir/concurrent/ThreadedExecutor.cpp.o
[ 32%] Building CXX object CMakeFiles/wangle.dir/concurrent/CPUThreadPoolExecutor.cpp.o
[ 34%] Building CXX object CMakeFiles/wangle.dir/concurrent/Codel.cpp.o
[ 36%] Building CXX object CMakeFiles/wangle.dir/concurrent/GlobalExecutor.cpp.o
[ 38%] Building CXX object CMakeFiles/wangle.dir/concurrent/IOThreadPoolExecutor.cpp.o
[ 40%] Building CXX object CMakeFiles/wangle.dir/concurrent/ThreadPoolExecutor.cpp.o
[ 41%] Building CXX object CMakeFiles/wangle.dir/ssl/PasswordInFile.cpp.o
[ 43%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLContextManager.cpp.o
[ 45%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o
[ 47%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLUtil.cpp.o
[ 49%] Building CXX object CMakeFiles/wangle.dir/ssl/TLSTicketKeyManager.cpp.o
Linking CXX static library lib/libwangle.a
[ 52%] Built target wangle
make: *** [all] Error 2_
------------------------------------------------------
Content of $HOME/proxygen/proxygen/proxygen/wangle/wangle/gmock/src/gmock-stamp/gmock-download-*.log
CMake Error at gmock-stamp/download-gmock.cmake:22 (message):
  error: downloading
  'https://googlemock.googlecode.com/files/gmock-1.7.0.zip' failed

    status_code: 22
    status_string: "HTTP response code said error"
    log: Hostname was NOT found in DNS cache
    Trying 66.102.1.82...

  Connected to googlemock.googlecode.com (66.102.1.82) port 443 (#0)

  successfully set certificate verify locations:

    CAfile: none
    CApath: /etc/ssl/certs
  SSLv3, TLS handshake, Client hello (1):
  ^A
CMake Error at gmock-stamp/gmock-download-impl.cmake:9 (message):
  Command failed (1):

   '/usr/bin/cmake' '-P' '$HOME/proxygen/proxygen/proxygen/wangle/wangle/gmock/src/gmock-stamp/download-gmock.cmake'

The status code returned is 22 while trying to download gmock zip file whereas download-gmock.cmake compares with 0.

**Comment by cm0n** [comment]
For me is the compile problem solved by the newest commit https://github.com/facebook/proxygen/commit/f415a985234ada9d31466f2bda94b697eec4c1ef

Now i have issues on the test cases, they also reported in #112

**Comment by afrind** [comment]
Closing since your compilation is working and test issues are tracked in #112
