### ISSUE TITLE
Example on consuming external web service within request handler

### ISSUE THREAD

**Issue by diorahman** [facebook/proxygen#159]
Hi,

It is common to have code that consumes external web service within the request handler. Can we have an example on this case? E.g. call one of the APIs of https://openweathermap.org/api with non-blocking fashion within the request handler, then send back the response from the API to the client.

Thanks!

**Comment by afrind** [comment]
The proxy example is similar to this, except instead of forwarding the original HTTP message, you would just create a new one.

eg: from onRequest, or onEOM, you would use the HTTPConnector to establish a new session, from there create a new transaction and send your request.  The Handler object will receive the response and you can process it how you like.  If you stream it directly to the client (as the proxy does) the flow control code is also in the example.
