### ISSUE TITLE
Git Submodules

### ISSUE THREAD

**Issue by Maktm** [facebook/proxygen#180]
Since proxygen uses folly and wangle as dependencies, wouldn't it be easier to include them as submodules into the project? A simple command such as:

`git clone --recursive https://github.com/facebook/proxygen.git`

would pull all the required dependencies?

I noticed the files folly-rev.txt and wange-rev.txt under build/deps/github_hashes/facebook but I was under the impression that everything under build is for contributors since it's related to continous integration.

**Comment by dddmello** [comment]
Sounds like a good idea and something I'll look into.  For now those *-rev.txt files linked are auto updated and so things are kept in sync automatically and is a system I believe other open sourced Fb projects buy into.

**Comment by AdamDailyMotion** [comment]
on the same topic, I wanted to clone proxygen so I would have a stable release which I've checked and would not have different code running between different machines. The problem is that the deps script pulls the latest of folly, wangle and other libraries which defeats the whole purpose of my clone.
Any ideas how to solve this?

**Comment by afrind** [comment]
@AdamDailyMotion : you could locally modify the deps script to pin it to the folly/wangle head revisions.  I realize it's not ideal.

**Comment by afrind** [comment]
Closing old issue.  We're committed to the current system for now, but if this is still a pain point please reopen.
