### ISSUE TITLE
Memory leak in HTTPConnector on connectSuccess?

### ISSUE THREAD

**Issue by zhi-zhao-dailymotion** [facebook/proxygen#194]
Hi, 
We're using proxygen as an HTTP client. We maintence the `HTTPUpstreamSession` in order to reuse it, and only re-connect the `HTTPConnector` when necessary. 

However, during testing, we see consistent memory leaks when lots of re-connection happens in our service. And we found that inside `HTTPConnector::connectSuccess()` (which is called when a new connect succeeded) from `HTTPConnector.cpp` the `HTTPUpstreamSession` was created using `new` and passed to the `connectSuccess()` callback. Since it's created on a temporary raw pointer, it doesn't seem that proxygen is not going to delete it, and the destructor of `HTTPUpstreamSession` was declared as `private` so the callback can not delete it either.

Not sure what did I miss here, but it seems like a memory leak to me. I'm wondering what's the proper way to handle this or it's some kind of memory cost we have to take?

Thanks.

**Comment by afrind** [comment]
HTTPUpstreamSession is self deleting - it knows when it is done because it has received a TCP fin from the other side or you've asked it to drain() and all outstanding requests are complete.  You need to add it to a wangle::ConnectionManager if you want to engage the idle timeout logic which will also lead to an eventual shutdown/cleanup.

**Comment by zhi-zhao-dailymotion** [comment]
Thank you very much for the detailed explanation!
