### ISSUE TITLE
Remove SPDY and NPN support

### ISSUE THREAD

**Issue by siyengar** [facebook/proxygen#217]
It has been almost 3 years since HTTP/2 was standardized. In the next few days we're going to remove support for all versions of SPDY as well as NPN in proxygen. We observe from our metrics that the amount of SPDY requests that Facebook receives is too small to keep supporting SPDY. We recommend that all users move to HTTP/2. We believe this is a good way forward. Not only does HTTP/2 have better header compression, it is also constantly evolving with new features that improve performance. Thanks for using proxygen.

**Comment by psetevik** [comment]
Why not just deprecate it, but leave it there ? One can easily disable _use_ of SPDY by removing it from protocol string, both downstream and/or upstream Sessions. 

There could be corner cases requiring SPDY, in the field.

When the decision was made to open source PG,  was there an expectation that  others, outside of FB,  might actually start using the library ? And that future development just might need to account for such users, at least in part that requires not forcefully removing chunks of functionality ?

Add features in a way that is supportive of those external entities that committed to Proxygen (and entire Folly, Wangle, Fizz ecosystem) , enhance and fix bugs etc, but please dont  rip out entire protos, just because FB doesn't see much use for it.

What is going to be next - removal of HTTP/1.x ?

**Comment by afrind** [comment]
First note that it's been 18 months since this announcement and we haven't yet removed the code.  We still want to though.

I believe all the major browsers have removed SPDY support.  Do you have real use cases for SPDY right now, and if so what are they?  Can we help migrate these use cases to HTTP/2?  We acknowledge that some older browsers/apps won't be able to speak SPDY anymore, but will fall back to HTTP/1.x.  Yes, when we open-sourced the library we anticipated and hoped others would begin using it.  We strive to keep APIs and such stable to support these users.  And of course we will never remove HTTP/1.x support :)

Note that even if we do remove SPDY, you are welcome to maintain a fork with the delete reverted to cover your own use cases.  We don't anticipate any major developments that would break it.

**Comment by MrAnno** [comment]
FYI:

Firefox: removed 3 years ago ([bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1248197), [patch](https://hg.mozilla.org/mozilla-central/rev/ea3d721baedc))
Chrome: removed 3 years ago ([deprecation](https://bugs.chromium.org/p/chromium/issues/detail?id=587469), [removal](https://bugs.chromium.org/p/chromium/issues/detail?id=624095))
Nginx: removed 4 years ago ([docs](https://nginx.org/en/docs/http/ngx_http_spdy_module.html), [commit](https://github.com/nginx/nginx/commit/ee37ff613fe2a746e23040a7a8aba64063123175))
Safari: deprecated in 2019 ([blog](https://webkit.org/blog/8569/removing-legacy-spdy-protocol-support/)), they will remove it soon

**Comment by psetevik** [comment]
Unfortunately, in "real world", it is not only browsers that act as clients. 

Lots of requests are programmatically generated and come from all sorts of APIs , left field and all. Quite a few are developed, pushed out into prod, but there's no active support of any sort. Yet, they are rightfully expected to continue working.

So, if one were to commit to FB's suite of Pg, Wangle, Folly, Fizz, Quic and develop products based on these, it would be extremely detrimental to see entire proto getting forcefully ripped out, just because Google removed support for it in Chrome etc.

Of course, no one expects FB to forever commit to supporting "dinosaurs".  Stop all dev, mark those as deprecated, but keep it there

**Comment by afrind** [comment]
Can you quantify the negative impact if we removed SPDY?  Do you know how many clients are using it?  Will they fall back to HTTP/1.1 or break entirely?

**Comment by psetevik** [comment]
These are all external entities/users/clients, virtually impossible to even ballpark extent of damage. Someone might have decided to use SPDY, in whatever framework/library/language that tickled their fancy, got it to work, has long moved on/left. Code continues to work and everyone's happy. 

So, during next refresh, when we link our product against latest git pull of PG and all of sudden SPDY is gone, could get nasty.  Downgrading to HTTP/1.1 would seem like a logical route to take, but again, there's just no telling.

The product is a reverse caching proxy. Whoever uses the product, have clients of their own, so hurt could spread pretty quickly and be impossible to control.

**Comment by afrind** [comment]
The most common way to negotiate SPDY Is using NPN, and any client doing it "correctly" would have a way to handle SPDY failing to negotiate, and fall back to HTTP/1.1.  This breakage seems  theoretical to me.  And sometimes we just need to clean house and drop old things that have been replaced by new things.  If a client breaks, they can upgrade to HTTP/2 (or HTTP/3!)  

The argument against just deprecating it and leaving it around is that there is a cost borne by all those who aren't using it: everyone is forced to compile the SPDY code and run the SPDY tests, etc.  And development is sometimes slowed by having to fixup things in the SPDY code when certain APIs change, etc.  

If maintaining SPDY support is critical to your product, you can still maintain a fork with the SPDY code.  Deletion is not imminent, but likely in the next 3 months.  We'll give an additional heads up here when we have a firm timeline.

**Comment by afrind** [comment]
SPDY support has been removed
