### ISSUE TITLE
Proxygen running environment?

### ISSUE THREAD

**Issue by nginxsantos** [facebook/proxygen#242]
I am evaluating proxygen as an http library for my application. I need both client and server support.

Can Proxygen work just a library to the application , i.e can it run inside the application thread?  Can it fit into the application’s a single epoll loop? Does ProxyGen fit the model where a single thread can be used to handle socket activity ?

Can I run Proxygen library without creating separate thread ? 

Can everything in this picture run inside the app  thread ? https://github.com/facebook/proxygen/blob/master/CoreProxygenArchitecture.png

It is a bit urgent, please help. Requesting @afrind please comment?

**Comment by ritunp** [comment]
Yes it is a library and will fit in with your application and it's single thread.

**Comment by badarihp** [comment]
@ritunp , i think HTTP Server run in multithreaded model, looking at HTPPServer.cpp start function which creates IOThreadPoolExecutor with a single thread and another IOThreadPoolExecutor ("HTTPSrvExec") as execution threads and the thread which invokes HTTPServer->start function will eventually loop forever ,  mainEventBase_->loopForever() ...

Can you provide an example of proxygen http server which runs in single threaded model ?

**Comment by afrind** [comment]
I think @ritunp was suggesting that proxygen can use a single thread, but it sounds like you want to run it within an application thread.  This can be done, with some caveats.

1. It will work best if your application thread is also driven by an event base (eg: application actions are triggered by I/O on a file descriptor, or a timeout).  Otherwise you will need to alternate doing application work and driving the eventBase that proxygen is running on (eg eventBase->loopOnce()).
2. You need to be careful that your application thread is not doing any work that might slow down the network I/O since they are all sharing the same thread.  

As for an example, I think you need to clarify how you envision your application thread and the event driven model for proxygen will cooperate first.

**Comment by jalopezsilva** [comment]
I believe all questions have been addressed. Closing this issue, feel free to re-open as needed.
