### ISSUE TITLE
Detect client close from a RequestHandler

### ISSUE THREAD

**Issue by kivikakk** [facebook/proxygen#252]
Is there a way to detect a client closing the connection in a `RequestHandler`?

I have a handler which pawns work off to a worker thread (see #240) — if the client closes the connection while I'm doing work, before starting to send my reply, I'd like to be able to detect this and just stop. I don't see anything on `RequestHandler` or `ResponseHandler` that lets me do this, however, and `HTTPTransaction` is a mysterious and sparsely-documented beast.

**Comment by afrind** [comment]
In some circumstances, your handler will get a requestError callback.  For example, if the connection is H2 and the client sends a RST_STREAM frame cancelling the request.  But if the connection is just closed with a TCP FIN, we don't treat this as an error, since the FIN only indicates the connection is half shutdown, and a response can still be generated.

We've toyed with the idea if dropping support for half-closed connections (in which case, receipt of a FIN would error all in-progress transactions), but haven't committed to implementing it.

**Comment by kivikakk** [comment]
Thanks for the response 👍  I'm using HTTP 1.1 in my case, and played around with various APIs to see if I could detect at various stages if the underlying transport was disconnected, but had no success. Good to know I'm not missing something!
