### ISSUE TITLE
Folding HQ/H3 into HTTPServer

### ISSUE THREAD

**Issue by psetevik** [facebook/proxygen#277]
As per afrind's suggestion, opening an issue:

#######################################################

Is there a plan to "fold" HQ into HTTPServer proper ?

Borrowing from sample EchoServer.cpp code, would love to have something like example below.

With 0 changes to existing app, incorporate support for QUIC and later on, H3, in part related to HTTP .

###################
using Protocol = HTTPServer::Protocol;

DEFINE_int32(http_port, 11000, "Port to listen on with HTTP protocol");
DEFINE_int32(spdy_port, 11001, "Port to listen on with SPDY protocol");
DEFINE_int32(h2_port, 11002, "Port to listen on with HTTP/2 protocol");
DEFINE_int32(h3_port, 11003, "Port to listen on with HTTP/3 protocol");**

...
HTTPServer server(std::move(options));
server.bind(IPs);

// Start HTTPServer mainloop in a separate thread
std::thread t([&] () {
server.start();
});

**Comment by yangchi** [comment]
@psetevik :
I took a closer look at both HQServer and HTTPServer. They are designed very different as it turns out. For example HQServers has a fixed list of supported paths and request handlers supplied by Dispatcher. HTTPServer on the other hand wants users to specify request handler via the HTTPServerOptions. The HQParams is specifically designed for the HQ binary cmdnline use-case. And HTTPServer has quite a bit of code that clearly had TCP in mind when written. I don't think it makes sense to just "fold" HQServer or HQ into HTTPServer as-is. Echo is actually one special case that folding can work since EchoServer and HQServer share the same EchoHandler. Anything else in the proxygen/httpserver/samples directory won't work with such a folding.

I guess we need some major refactor, or even a new server if we want to have proper support of both TCP and Quic in one server.

**Comment by lnicco** [comment]
if it can help you, currently the `hq` runs both http3 and http2 servers side by side, the handlers are shared and the HQParams can be shared between the two. However that is not currently seamless and requires writing quite some glue code
You can follow `startServer() ` in `proxygen/httpserver/samples/hq/HQServer.cpp`
and see what we do for handlers in `proxygen/httpserver/HTTPTransactionHandlerAdaptor.h`

**Comment by psetevik** [comment]
Some  apps were developed based on the HTTPServer, RequestHandler and RequestHandlerFactory framework.

HTTPServer supports HTTP/1.x, H2. So if HTTPServer were to add support for H3, those
apps wont have to change at all. A simple flag in HTTPServerOptions and boom, we're done, complete trifecta of protos, 0 effort, same pool of IO Workers handling entire everything.

The other route leads to segregation: dedicating a set of IO Worker threads to H3/H2, while requiring separate pool to support H1, kind of sucks.  And having to adopt Hq to support RequestHandler and RequestHandlerFactory,  thats an effort too.

I understand beggars cant be choosers, but I was under impression HTTPServer will be supported going forward, including adding H3, so I committed to it. Was really surprised to see Hq enter the stage.

**Comment by yangchi** [comment]
I'm working on some diffs to support Quic in HTTPServer. The first version will be a bit awkward though - most existing APIs in HTTPServer will still be TCP only and Quic settings needs to be passed in from HTTPServer ctor. I think after that we can keep refactoring the APIs. The diffs will be posted soon.

**Comment by psetevik** [comment]
That would be very sweet. Most of what H3 requires, already are passed (to HTTPServer) through options, including multiple certs/keys. 

Having looked at H3 sample impl, seems it only takes a single cert/key pair currently ? 

Do you think same pool of IO Workers/threads could tend to all of the Sessions - including H3, H2 and H1 ?

**Comment by yangchi** [comment]
sorry the "soon" wasn't soon enough. It's under diff review internally.

**Comment by yangchi** [comment]
The API may be different from what you proposed though. But we can work towards there once we get the first version work.

**Comment by psetevik** [comment]
How is it proceeding ?  Will look under the tree tomorrow :)

**Comment by yangchi** [comment]
Next month :)

**Comment by yangchi** [comment]
Here is an update: sorry for the super long waiting time on this. I am very unhappy about the result of this folding. After the diff being worked on for months and going back and forth  with other people on the team in diff reviews, I think I will drop it. :(

It works. But it's an very ugly Frankenstein.

**Comment by yangchi** [comment]
Here are some notes I can leave here in case others would like to do this properly:

Instead of folding HQ into HTTPServer, we should actually design a new server from the ground up. All the current APIs in HTTPServer has assumption of TCP based transport and such interfaces. The HTTPServerOptions is also very TCP and HTTP/2 oriented. Folding HQ into it, while combining   HTTPServerOptions interfaces and HQParams interfaces together into one class, although can work, turned out to be very ugly.

There is also this strange dependency problem I don't like to deal with. One is that for any real meaningful use of this new server, HQParams and the current sample handlers need to be used. However we don't want anything directly under proxygen/httpserver/ to depend on anything in samples/. I worked around that, but that's also ugly and makes the code quite arbitrary and i had to dynamic_cast in one place which I also don't like.

The other dependency problem is that Quic itself is an optional dependency in Proxygen. For us that's not a problem. But for OSS code, it makes the cmake files quite messy.

**Comment by yangchi** [comment]
I'm closing it since there hasn't been any activity since I abandoned my diffs.
