### ISSUE TITLE
Does HTTP/3 support parallel streams?

### ISSUE THREAD

**Issue by Enjia** [facebook/proxygen#303]
I saw the notes in HTTPParallelCodec.h saying:

> An implementation of common codec functionality used for multiple parallel stream downloads. Currently shared by SPDY and HTTP/2

Does that means when run ./hq based on HTTP/3 there just exists one stream? Because when I add -v=4 or -v=10 in cmdline I just got one StreamID. And is this the main reason that in HTTPSession::setupCodec the maxConcurrentIncomingStreams_ and maxConcurrentIncomingStreams_ are both set to 1 when maxConcurrentIncomingStreams_ is False using HTTP/3? Thanks

**Comment by afrind** [comment]
It does support parallel streams, but at the transport rather than the codec level.  HQStreamCodec returns false for supportsParallelStreams(), because there is only ever one stream processed by one codec.  Contrast this with H2 (or SPDY), where a single codec processes all streams.

HTTPSession does not process H3 connections.  See HQSession instead.

If you want HQ client to create multiple streams, pass a list of URLs instead of single URL, and they will be fetched in parallel.
