### ISSUE TITLE
Transfer large files after modifying some codes

### ISSUE THREAD

**Issue by Enjia** [facebook/proxygen#307]
Hi, when transferring large file (eg. 5G, connect successfully), client threw out an error : [CurlClient.cpp]Got error=LocalError:No Error, Exceeded max PTO. 
**So the first question is that what causes PTO timeout.**
However if I test mvfst alone instead of proxygen, there's no such exception.

The strange thing is that if I modify the codes in SampleHandlers.h:

> folly::getCPUExecutor()->add(std::bind(&StaticFileHandler::readFile, this, folly::EventBaseManager::get()->getEventBase()));

into:

> readFile();

that is to say  I skip the CPUExecutor, I can transfer the large file no matter what size it is. **I wonder whether  such modification will leave some hidden troubles skipping the CPUExecutor or do you guys have any other good idea of transferring large files? Thanks!**

**Comment by afrind** [comment]
Sorry we didn't engage here sooner.  You don't want to read the file (perform disk IO) in the I/O thread.  In fact, I might expect the PTO timeout to be more likely when you are blocking the event base?

As for why you get a PTO timeout when the disk I/O is offloaded I'm not sure.  @yangchi since you engaged on the other issue, do you have any thoughts here?

**Comment by yangchi** [comment]
too old. close. sorry you will need reopen a new issue if you still have problem with large transfer
