### ISSUE TITLE
How to stop on-going requests before call HttpServer::stop()?

### ISSUE THREAD

**Issue by critical27** [facebook/proxygen#317]
Hi, since some requests could take quite a long time, it would block when we call HttpServer::stop(). How to stop those on-going requests? Thanks a lot.

**Comment by afrind** [comment]
Wow, we really let you down and didn't get an answer to your simple question for 4+ years, but in our defense, it was the beginning of the pandemic.

To quickly answer: 

We tend to handle graceful shutdowns by stopping accepting new work.  Often there is a load-balancer in front of a proxygen server that sends a periodic health check request to a specific endpoint (eg: /health).  Once graceful shutdown is initiated, this endpoint returns non-success, and new traffic will be routed to other servers.

HTTPServer::stopListening will also stop accepting new work at the current server.  If you have work that needs an additional signal in order to graceful shutdowns (eg: a long poll request to a long running endpoint), the framework doesn't have a specific way to signal that now.  HTTPServer::forEachAcceptor may be useful.
