### ISSUE TITLE
HTTP2 Protocol Error 

### ISSUE THREAD

**Issue by SteveSelva** [facebook/proxygen#498]
I have modified the sample "proxygen_proxy" to work as a proxy server. 
There I came up with a issue in HTTP2 Protocol. 
I have configured the proxy server to limit maxConcurrentIncomingStreams = 100. 
And a connection is established through proxy server, both Downstream and Upstream uses HTTP2 Protocol for communication. 
Upstream sets MAX_CONCURRENT_STREAMS = 100 using SETTINGS Frame.
When the transaction id of the session = 201(upstream stream id = downstream stream id), the Upstream server returns PROTOCOL_ERROR as response and aborts the stream and all the other streams get closed with StreamUnacknowledged error.
But when I see the logs from HTTPSession::InfoCallback, I can see that logs from function: onTransactionDetached() on that Upstream Session. So I think the streams are closed too. 
When I print the number of active streams, number of incoming streams and number of outgoing streams on onServerError() function in ProxyHandler, their values is also less than 100.
And I have confirmed multiple types the StreamAborted message in onServerError() function when the StreamID is 201. 

Why is it happening? 
Is the Streams are not properly closed in Upstream causing MAX_CONCURRENT_STREAMS > 100 to throw PROTOCOL_ERROR?

Can you provide a solution to fix this issue.

**Comment by afrind** [comment]
Can you share a snippet of your code fix?

There's definitely some friction in proxies because the onHeadersComplete codec callback doesn't include the END_STREAM flag, so it can be challenging to immediately pass through to an upstream without making an assumption (eg: GET == END_STREAM) or delaying an event loop so the onEOM downstream callback fires.

I've even tried fixing this once, but ran into some complications.
