### ISSUE TITLE
ClientSilent

### ISSUE THREAD

**Issue by SteveSelva** [facebook/proxygen#527]
May I know what are the reasons ClientSilent error occurs?

And how to fix it?

**Comment by afrind** [comment]
It comes from here:

https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/session/HTTPSession.cpp#L584-L590

We fire this error if someone opens a TLS connection and closes it without sending any requests.  The comment there explains, but one reason this might happen is if the client didn't like the server's certificate (expired?), so we surface this as an error rather than ignore it completely.

You can ignore the error if you choose, since it could just be annoying clients opening and closing connections, but it might also be indicative of something you are doing that is causing the clients to go away.

**Comment by afrind** [comment]
@SteveSelva : in this case, it's the client verifying the server's part of the TLS handshake.   They need to check the signature, notBefore / notAfter and that the trust the CA, among other things.
