### ISSUE TITLE
ZlibStreamCompressor is not supporting -1 compression level

### ISSUE THREAD

**Issue by floatdrop** [facebook/proxygen#89]
When building DEBUG version of proxygen echo example and opening page with browser I get an exception:

```
F0420 11:45:21.513430 11128 ZlibStreamCompressor.cpp:54] Check failed: level_ >= 0 && level_ <= 9 Invalid Zlib compression level. level=-1
```

It comes from [this line](https://github.com/facebook/proxygen/blob/739166b5fedee51d6f4d4cf0c7e54280d083b84a/proxygen/lib/utils/ZlibStreamCompressor.cpp#L54), because default value in [HTTPServerOptions.h](https://github.com/facebook/proxygen/blob/739166b5fedee51d6f4d4cf0c7e54280d083b84a/proxygen/httpserver/HTTPServerOptions.h#L102-L106) is `-1`.

This is easy to fix just by setting `contentCompressionLevel ` option to right value, but description says, that `-1` is valid value:

> Zlib compression level, valid values are -1(Default) to 9(Slower).

Should this check be fixed or default value set to `0`?

**Comment by lnicco** [comment]
Hi @floatdrop, you mentioned that this only happens when building with DEBUG ? 
I'm looking into this issue and am trying to reproduce it; could you please paste the exact command you used to build ?

**Comment by floatdrop** [comment]
@lnicco yes, [`DCHECK`](https://github.com/facebook/proxygen/blob/739166b5fedee51d6f4d4cf0c7e54280d083b84a/proxygen/lib/utils/ZlibStreamCompressor.cpp#L54) is only working, when [`NDEBUG`](https://github.com/google/glog/blob/4d391fe692ae6b9e0105f473945c415a3ce5a401/src/glog/logging.h.in#L979) is not defined, which is true for Debug build mode, but not for Release.

Exact command to build:

```
/usr/bin/g++ -std=c++1y -o CMakeFiles/echo_example.dir/main.cpp.o -c main.cpp
```

If you add `-DNDEBUG` flag, `DCHECK` will be disabled.

**Comment by lnicco** [comment]
@floatdrop you are right that when setting `enableContentCompression` the compression level should also be set, and I am going to fix that.

There are however a couple of other things that are puzzling me as how you were able to trigger this.

With the latest code there are in fact two separate checks that are preventing compression to take place: 

1_ the response content type should be one of these: https://github.com/facebook/proxygen/blame/master/proxygen/httpserver/HTTPServerOptions.h#L111
And EchoHandler does not include any `Content-Type` header.
This can be simply fixed by adding a "Content-Type: text/html" here: https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/echo/EchoHandler.cpp#L39

2_ the minimum content size to enable compression is set at its default value (1000). 
what request are you sending exactly ? Does it have a body larger than 1000 bytes ?

You must have some local changes in order to trigger this, am I right ? 
Or were you able to trigger the crash on a fresh clone of the repo ?
If the latter is true, I'd like to know more, about your setup and on which request you sent to the server, 
you mentioned using a browser, could you post the details ?

**Comment by lnicco** [comment]
on a second thought it makes sense to set  `enableContentCompression = false`
as the echo server should really send back exactly what it received, without compressing

**Comment by floatdrop** [comment]
> And EchoHandler does not include any Content-Type header.

@lnicco yep, I modified example here and there and set `Content-type` to `application/json`, which probably was larger than 1000 bytes.

**Comment by lnicco** [comment]
Thanks for the clarification @floatdrop,

Issue resolved here:
https://github.com/facebook/proxygen/commit/43146b064059e5779aa3be18e8214b291074dfa4
